# Generated by Django 4.2.16 on 2024-09-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="vehiculos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(default="ford", max_length=20)),
                ("modelo", models.CharField(max_length=100)),
                ("serial_carroceria", models.CharField(max_length=50)),
                ("serial_motor", models.CharField(max_length=50)),
                ("categoria", models.CharField(default="particular", max_length=20)),
                ("precio", models.FloatField()),
                ("fecha_de_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_de_modificacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
