# Generated by Django 4.2.16 on 2024-09-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="vehiculos",
            new_name="Vehiculo",
        ),
    ]
