# Generated by Django 4.2.16 on 2024-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0002_rename_vehiculos_vehiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="categoria",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="fecha_de_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="marca",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="precio",
            field=models.IntegerField(),
        ),
    ]
