# Generated by Django 5.1.1 on 2024-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0003_alter_vehiculo_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Particular", "Particular"),
                    ("Transporte", "Transporte"),
                    ("Carga", "Carga"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="marca",
            field=models.CharField(
                choices=[
                    ("Fiat", "Fiat"),
                    ("Chevrolet", "Chevrolet"),
                    ("Ford", "Ford"),
                    ("Toyota", "Toyota"),
                ],
                max_length=20,
            ),
        ),
    ]
