# Generated by Django 5.1.1 on 2024-09-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0004_alter_vehiculo_categoria_alter_vehiculo_marca"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiculo",
            options={
                "permissions": [
                    ("visualizar_catalogo", "Puede visualizar el catálogo de vehículos")
                ]
            },
        ),
    ]
